services:
  - type: web
    name: dosttan-backend
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      npm install
    startCommand: |
      npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5050
      - key: DATABASE_URL
        fromDatabase:
          name: dosttan-db
          property: connectionString
      - key: REDIS_HOST
        value: red-d3vmp72li9vc73cvuud0
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        value: ""
databases:
  - name: dosttan-db
    databaseName: dosttan
    user: dosttan_admin
    plan: free
    region: oregon
