/**
 * Return Request Model
 * Handles product return requests from customers
 */

const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/sequelize');

const ReturnRequest = sequelize.define(
  'ReturnRequest',
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    return_number: {
      type: DataTypes.STRING(50),
      allowNull: true, // Generated by beforeCreate hook
      unique: true,
      comment: 'Human-readable return number (e.g., RET-2024-00001)',
    },
    order_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'orders',
        key: 'id',
      },
      onDelete: 'RESTRICT',
      comment: 'Related order',
    },
    user_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'users',
        key: 'id',
      },
      onDelete: 'RESTRICT',
      comment: 'Customer who requested return',
    },
    store_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'stores',
        key: 'id',
      },
      onDelete: 'RESTRICT',
      comment: 'Store handling the return',
    },
    status: {
      type: DataTypes.ENUM(
        'pending',
        'approved',
        'rejected',
        'items_received',
        'refund_processed',
        'completed',
        'cancelled'
      ),
      defaultValue: 'pending',
      allowNull: false,
      comment: 'Return request status',
    },
    reason: {
      type: DataTypes.ENUM(
        'defective',
        'wrong_item',
        'not_as_described',
        'damaged',
        'changed_mind',
        'better_price_elsewhere',
        'other'
      ),
      allowNull: false,
      comment: 'Reason for return',
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: false,
      comment: 'Detailed explanation from customer',
    },
    items: {
      type: DataTypes.JSONB,
      allowNull: false,
      comment: 'Array of items to return: [{order_item_id, quantity, reason}]',
    },
    images: {
      type: DataTypes.ARRAY(DataTypes.TEXT),
      defaultValue: [],
      comment: 'Evidence images uploaded by customer',
    },
    refund_amount: {
      type: DataTypes.DECIMAL(10, 2),
      allowNull: false,
      comment: 'Amount to be refunded',
    },
    refund_method: {
      type: DataTypes.STRING(50),
      defaultValue: 'original_payment_method',
      comment: 'How refund will be processed',
    },
    store_response: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: 'Response from store (approval/rejection reason)',
    },
    approved_by: {
      type: DataTypes.UUID,
      allowNull: true,
      references: {
        model: 'users',
        key: 'id',
      },
      onDelete: 'SET NULL',
      comment: 'Store owner/admin who approved/rejected',
    },
    approved_at: {
      type: DataTypes.DATE,
      allowNull: true,
    },
    rejected_at: {
      type: DataTypes.DATE,
      allowNull: true,
    },
    items_received_at: {
      type: DataTypes.DATE,
      allowNull: true,
      comment: 'When store received returned items',
    },
    refund_processed_at: {
      type: DataTypes.DATE,
      allowNull: true,
      comment: 'When refund was processed',
    },
    completed_at: {
      type: DataTypes.DATE,
      allowNull: true,
    },
    cancelled_at: {
      type: DataTypes.DATE,
      allowNull: true,
    },
    cancellation_reason: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    tracking_number: {
      type: DataTypes.STRING(100),
      allowNull: true,
      comment: 'Return shipping tracking number',
    },
    carrier: {
      type: DataTypes.STRING(100),
      allowNull: true,
      comment: 'Return shipping carrier',
    },
    admin_notes: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: 'Internal notes for admin',
    },
  },
  {
    tableName: 'return_requests',
    timestamps: true,
    indexes: [
      {
        unique: true,
        fields: ['return_number'],
      },
      {
        fields: ['order_id'],
      },
      {
        fields: ['user_id'],
      },
      {
        fields: ['store_id'],
      },
      {
        fields: ['status'],
      },
      {
        fields: ['created_at'],
      },
    ],
  }
);

// Return Status State Machine
const RETURN_STATUS_TRANSITIONS = {
  pending: ['approved', 'rejected', 'cancelled'],
  approved: ['items_received', 'cancelled'],
  rejected: [],
  items_received: ['refund_processed'],
  refund_processed: ['completed'],
  completed: [],
  cancelled: [],
};

// Instance Methods

/**
 * Check if status transition is valid
 * @param {string} newStatus
 * @returns {boolean}
 */
ReturnRequest.prototype.canTransitionTo = function (newStatus) {
  const allowedTransitions = RETURN_STATUS_TRANSITIONS[this.status] || [];
  return allowedTransitions.includes(newStatus);
};

/**
 * Transition to new status with validation
 * @param {string} newStatus
 * @param {Object} metadata - Additional data for the transition
 * @returns {Promise<boolean>}
 */
ReturnRequest.prototype.transitionTo = async function (newStatus, metadata = {}) {
  if (!this.canTransitionTo(newStatus)) {
    throw new Error(`Cannot transition from ${this.status} to ${newStatus}`);
  }

  this.status = newStatus;

  // Update timestamp fields based on status
  const now = new Date();
  switch (newStatus) {
    case 'approved':
      this.approved_at = now;
      if (metadata.approved_by) {
        this.approved_by = metadata.approved_by;
      }
      if (metadata.store_response) {
        this.store_response = metadata.store_response;
      }
      break;
    case 'rejected':
      this.rejected_at = now;
      if (metadata.approved_by) {
        this.approved_by = metadata.approved_by;
      }
      if (metadata.store_response) {
        this.store_response = metadata.store_response;
      }
      break;
    case 'items_received':
      this.items_received_at = now;
      if (metadata.tracking_number) {
        this.tracking_number = metadata.tracking_number;
      }
      if (metadata.carrier) {
        this.carrier = metadata.carrier;
      }
      break;
    case 'refund_processed':
      this.refund_processed_at = now;
      break;
    case 'completed':
      this.completed_at = now;
      break;
    case 'cancelled':
      this.cancelled_at = now;
      if (metadata.cancellation_reason) {
        this.cancellation_reason = metadata.cancellation_reason;
      }
      break;
  }

  await this.save();
  return true;
};

/**
 * Check if return can be cancelled
 * @returns {boolean}
 */
ReturnRequest.prototype.isCancellable = function () {
  return ['pending', 'approved'].includes(this.status);
};

// Class Methods

/**
 * Generate unique return number
 * @returns {Promise<string>}
 */
ReturnRequest.generateReturnNumber = async function () {
  const year = new Date().getFullYear();
  const prefix = `RET-${year}-`;

  // Find last return number for this year
  const lastReturn = await this.findOne({
    where: {
      return_number: {
        [sequelize.Sequelize.Op.like]: `${prefix}%`,
      },
    },
    order: [['created_at', 'DESC']],
  });

  let nextNumber = 1;
  if (lastReturn) {
    const lastNumber = parseInt(lastReturn.return_number.split('-').pop(), 10);
    nextNumber = lastNumber + 1;
  }

  return `${prefix}${String(nextNumber).padStart(5, '0')}`;
};

// Hooks

/**
 * Generate return number before creating
 */
ReturnRequest.beforeCreate(async (returnRequest) => {
  if (!returnRequest.return_number) {
    returnRequest.return_number = await ReturnRequest.generateReturnNumber();
  }
});

/**
 * Validate status transitions before update
 */
ReturnRequest.beforeUpdate(async (returnRequest) => {
  if (returnRequest.changed('status')) {
    const oldStatus = returnRequest._previousDataValues.status;
    const newStatus = returnRequest.status;

    const allowedTransitions = RETURN_STATUS_TRANSITIONS[oldStatus] || [];
    if (!allowedTransitions.includes(newStatus)) {
      throw new Error(`Invalid status transition from ${oldStatus} to ${newStatus}`);
    }
  }
});

module.exports = ReturnRequest;










